---
# Site
baseURL: "http://opentechschool.org/"
languageCode: "en-us"
title: "OpenTechSchool"
enableRobotsTXT: true
googleAnalytics: ""
# Content
languageCode: "en-us"
defaultContentLanguage: "en"
# Formats
metaDataFormat: "yaml"

sectionPagesMenu: "navigation"

contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
# -----------------------------
# DO NOT CHANGE BELOW THIS LINE
# -----------------------------
disableLiveReload: true
watch: false
---
