# Site settings
title: OpenTechSchool
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  OpenTechSchool is a community initiative to
    provide programming and other tech-related workshops to women and their
    friends of all genders. We take care of the organizational side of things
    (venues, press, finding participants) and let our volunteer coaches to create
    the curriculum according to their vision. Our main goal is to create a
    friendly and safe learning environment where no one feels shy about asking any
    question. Everyone, no matter what their gender, skill level or experience, is
    invited to participate, whether as a coach or a learner
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://opentechschool.org" # the base hostname & protocol for your site
twitter_username: OpenTechSchool
twitter_url: twitter.com/OpenTechSchool
github_username:  OpenTechSchool
github_url: github.com/OpenTechSchool
forum_url: discourse.opentechschool.org

# Build settings
markdown: kramdown

exclude:
  - vendor
  - README.md
  - Gemfile*
  - .gitignore

collections:
  chapters:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      does:
        - workshops
