baseURL = "http://opentechschool.org/"
languageCode = "en-us"
title = "OpenTechSchool"
MetaDataFormat = "toml"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"


[params]
  email = ""
  description = '''
      OpenTechSchool is a community initiative to
      provide programming and other tech-related workshops to women and their
      friends of all genders. We take care of the organizational side of things
      (venues, press, finding participants) and let our volunteer coaches to create
      the curriculum according to their vision. Our main goal is to create a
      friendly and safe learning environment where no one feels shy about asking any
      question. Everyone, no matter what their gender, skill level or experience, is
      invited to participate, whether as a coach or a learner
      '''
  twitter_username = "OpenTechSchool"
  twitter_url = "twitter.com/OpenTechSchool"
  github_username = "OpenTechSchool"
  github_url = "github.com/OpenTechSchool"
  forum_url = "discourse.opentechschool.org"
  MEETUP_KEY = "38406b383fa43605b6b234269316"
